// <auto-generated />
namespace WebSite.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class MakeSubscriptionOptionalForUsers : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207170508122_MakeSubscriptionOptionalForUsers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOVc224juRF9D5B/EPopCbCSrEEWswN5Fx6NHQjxDSPP7KNBd9MysX1RmpTX+rY85JPyC0v2ldcm+yJZSt5kNnlYLBaL1dV1/N9//2f+y1sUjl5hilESn3tn46k3grGfBChen3tb8vzDR++Xn//8p/llEL2Nvpf9ZqwfHRnjc++FkM2nyQT7LzACeBwhP01w8kzGfhJNQJBMZtPpx8nZdAIphEexRqP5121MUASzP+ifiyT24YZsQXiTBDDERTt9sspQR7cggngDfHju/QqfVojA8RdAwBPA0BtdhAhQOVYwfG4p1PQnJpRXTUcnvKSCkd3DbgOzSc+9bximfA/a559wJzTQpvs02cCU7L7CZ27cMvBGE3HsRB5cDZXGMRHOvWVMPsy80e02DMFTSBueQcjWvPnx04okKfwHjGEKCAzuASEwpVuzDGC2hEIVnzY/umnjp8l0xrQxAXGcEEDoPivCS6KWU9HmVxRQNVmEboe2xHgLA1EdK5JSw/RGV+gNBtcwXpOXCv0GvJUtf6fW+S1G1IzpGJJuYWthLiOAwosgSCHGLSc/m/ae/QqlmLCfB1/3NXiniZf4MzU8WO305yQJIYhb46zQOv62oc6hWgL7/YCibrq4TtYoHgTtIUUgvHzboHQ3CN5q+4T9FG3YQW3wF/lmuENd+AS9ZqffJmVb5AWgTp4O7ox9C17ROhveMIs3+grzOfAL2uS3wpg5kUex11WaRF+TsHC4wsPHVbJNfSZfYurxANI1JO4SMhxsFq14LMmUteqFyR/ppJhP6hus8V4T1NHhfpPtr+0952i/x3Tf3afIr80W+igCoTe6T+mvInz66I1WPmBy2+4/531iW91lf9i4LvtSjjuB/ehwUc1aXlTux4kk/m+/I3qFpfgGRk/dgsZ8ZJdtq0eewMb9H8Y3fQLK/rPfA4x/T9K2cfQAoewSX8M18HfFmWgV3TkfvkUKA0QWgC6ww6GrR3c5eOLo"
                       + "Ezh8TNSXJKRvWB0OwgAWcbvlLcFxXvqz9wnMYu/ecffi+/dewXbhA+zG4hpbfkZhSFVY+RZNkFnb6KPcu445jZ2UENTcs1dEWsrU4QhzSm17fp334ygObyHtNYrh2eGPLjf77PCzZ4kh+g55l64I9/7oKMCH/vMnmIBwQQH2HHRqnE6yjUm6G85pFIBab1Ee5qpP7SOkR4pnkJ/38gfl/F2u9Fpfre9zV1UfhT84QCxr2q8LjBMfZVJyqevHhrzCZRyMrDmXfCllaoRKvg0J2oTIpyKce39TFNIEWpofBypmgUTw6Xh8puBTo4Ip20929GNMUoBiologdUxoA0KbKNLADpkVtiHVdPKTL3ADY2Z9Nj0PI0c1nXTGbDqbTzjjcbCpPD/WuO9SsqzZirQbrQXUWFCWkGk2yxbrk52tSSaj560Fq2I69yNj8tccanULiKhnsgnN7+IvMIQEjlgKmWXDFgD7IFAvJepPggHOmEF2F8s2Xg+tDpdhS3oLcIBTZX4hMFmKw9sBZzP1+3gLY7S/VtiN/f3N0roKF/swvs+0MlDrnvUWZXBTzUMNOobQETAtZCi/9bN2+EYUI2VjVpBwVwY1jDpqEW4CxfzEwfylpwMR4wcLWPFdRwHJrxCbJEpGWSuPmne2AddmoQPkz64FqDAN7RKr82kTJvOESItRXT0SBmc74q5L3/i4fsYPgbJJu8So1RoqW1NOhktUysFIVid7JnHBrsoorM+gBU1MZYuq2q9bDKK48YVsvReqvKuqq22MsJxiLE5uzuQb1m4Kqzggzu57K6Ehvaeqw/Hqb3n58yvj3UuDkuzXvYveG9RVvrhWt0n1bD7J68qKhvnEUIA2vwGbDRWMK0grWkarvBpt8cOqfc1ZlGNMfKwpPaukrWYiSQrWUHrKLCiA2Ye0uhJuEURKN8e7s5yNv0LVvSsddNmb/c5HyGV5Y7VujtffFV1SxCKVLIUiORZ12IhVAoIQpIZiuUUSbqO4"
                       + "qfCuCUWtY+Px1KfdkcWatqZZxJ7uM4rfGfkZxCfuiNzHWh6Oa3bHqj+/8lB1awvNVvVigharVnckvmKMx+Lb262QKxqTl8k9csdUSsd4VOVhi5VLCR5h9ZbkjxuqXE1mmkHu1202tcLMNJ/aU51xPpF8lfL2o/hD5YVSdK5OrlcMBXu54KZA18EVNw8/rFEVpVc8WNF0NBtnCqhbbJha6+W0UfphJlWWBV68LvXFYk0oqhc3efD3Okea1+d+p8lS4eW0VS4gJpXXJV682k0lY01Ix3mlDx+61GVPguOoWtuEG2IZkxh0iM+O5gjwb2K9TN9UX5Uh2Uy+abBJ3WJRFa/spmKtRkSp6knAlJ618IJb1RzKthaGX1QmCSZftLVYIStMEpbFGtzHc4leHqUh//tuhl1nA3qZtSHx4WDTxpFDKteCVdQAaeCKJ50QZ0bEWbt4TarVESM36WELXK4GR4Dk2lscmfoznHBwzF/n3s+XV/nCfp5cnwR1ceOmkUMq9/ijTTHbqGbNyqy7JTNWdnMJ5VnOVJP3EpPzqiJaJcweTZmm7LNoCdJKMOPnzt5vJY0yLZKYBgjsU/cSs7qmqqbJcclyQlm1AiWvLHepbLDKL0t55HmR07WznZUkb96FsY7yPCF9pdhhAqPMvMarf4WLEFGrrzvcgBg9Q0wekt8gY25Ppx+7U6arCjWMg/CYedOIqcBanteToSxMtge2c/wKUv8FpEr53gDcEy12VqTbl6s8lNQyVWcoXJlp/ITa757KMg7obzIYy7gzmoFl3BlPz9KUDH4YjrFOxqE4xm7YJ86d3YvPEzivURJDG8SJEFv3oiyru5q1d1dCqOJ4/E6WtbqXXTm5G8r9vu4ALlNBBwsE9ExP++16sizPvRirnp052CaJ5MsS9i8RePtrT0Jl5xCDI1R2iCsU+p49GD81QuJe7ExHJBzMynQ8wcHADTRALf6HDvAKy2+om1xhlg1oqkfClXufqMp6C+6D"
                       + "wiaWGvdhmIk1sx0ocJ14CpbikL3T0v7nKGh9WWc5KaAd0azr5jtvgDkt7LzZhqIW/VwNeeijpEXJ/9HlUNQkXRl1ZwpWH/rdu9CZjpC41J3ZWVEXDky67GTEAxmP+TPknsmaR8jO1FPe1Op+efdU0puR85Z/NKLvaE8J3eQ8TNIyeBrpcFY2nG6aZmaTjjBn5Mvp4PU8IjuVzpFJp12RjpfnTLmzMO50EzYQakyUvCZCnm4KM71Gz9fbNbH1tGsw0p0OQ+bT2bFa5GzjsykUuOOh6llF08Sact3BCTDRJPsWirHcyGYGrtqxcRGlcyaU4DhQD10UNAx1Ti1loHch9+/d6U2M0bqGYAUaMfSFW7Dqs4yfk/I+liQquyhfEAgI6BV5kRL0DHxCH/t0rdk/wvkOwm2WTn+CwTK+25LNltAlU58dCkpkl3rT/Bk/UJR5fpffaEMsgYqJWPb0Lv68RWFQyX2lSWQYIFi0UGRc2F4SlnlZ7yqk2yR2BCrUVwU5DzDahBQM38Ur8ArNstl1KGps/gWBdQoiXGDU4+mf1PyC6O3nPwAsMq7QoGAAAA=="; }
        }
    }
}
