// <auto-generated />
namespace WebSite.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class SubscriptionTypeForAddOns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SubscriptionTypeForAddOns));
        
        string IMigrationMetadata.Id
        {
            get { return "201304242217083_SubscriptionTypeForAddOns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
